# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_auto_20160607_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
